### ISSUE TITLE
bug when '=' follows by '\x01'

### ISSUE THREAD

**Issue by nanzeng** [jamesdbrock/hffix#15]
In the message_reader_const_iterator::increment(), there is no check for this invalid message when tag value is missing. The const iterator will pass the '\x01' next to '=' and search for the next available '\x01'.

current_.value_.end_ = ++current_.value_.begin_;

+  if (*current_.value_.begin_ == '\x01') {
+     return;
+  }

will fix this problem.

**Comment by jamesdbrock** [comment]
Thanks for the bug report @nanzeng ! I pushed a test for this issue, and a bug fix.
