### ISSUE TITLE
MaxMessageSize is NOT a data length field

### ISSUE THREAD

**Issue by andreig1978** [jamesdbrock/hffix#44]
Because it is marked as such, it causes the following field to be treated as a data field (having the length specified by MaxMessageSize) and can cause an invalid memory access (outside the buffer). As a side note, when parsing data fields, it might be a good ideea to check whether the data field length is valid (smaller than the remaining buffer size).

**Comment by andrei-gheorghe-1978** [comment]
Also, the increment() method assumes another field will follow a data length field which again can put you outside the message buffer.

**Comment by andrei-gheorghe-1978** [comment]
I am wondering if it wouldn't be better to parse the field where the iterator is de-referenced (message_reader_const_iterator::operator*()) and not where it is incremented.

The issue that I see is that:
`inline void message_reader_const_iterator::increment()
{
    buffer_ = current_.value_.end_ + 1;` // <- here **this** might equal **message_reader::end()**

    // <- here you are parsing stuff past the buffer end (the parsed data shall not be used but still it seems wrong to do this)
}

Please let me know what you think.

**Comment by jamesdbrock** [comment]
Thanks, I'll check this out.
